# Generated by Django 4.1.1 on 2022-09-29 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('color', models.CharField(choices=[('Black', 'B'), ('White', 'W')], default='', max_length=225)),
                ('price', models.IntegerField()),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('f_assured', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='product/images')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.category')),
            ],
        ),
    ]
